name: Deploy to Heroku

on:
  push:
    branches:
      - main # Set this to the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is a GitHub Action created for Heroku deployments
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: munrodj86@gmail.com
