name: Deploy to Heroku

on:
  push:
    branches:
      - main # Set this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # - name: Deploy to Heroku
      #   uses: akhileshns/heroku-deploy@v3.13.15 # Use the latest version
      #   with:
      #     heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
      #     heroku_app_name: 'simple-lims'
      #     heroku_email: 'munrodj86@gmail.com'

      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }} // Heroku email address
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }} // Heroku API key
          heroku_app_name: ${{ env.HEROKU_APP_NAME }} // Declared above
          justlogin: true

      - name: Add Heroku remote
        run: heroku git:remote --app=${{ env.HEROKU_APP_NAME }}

      - name: Push to master branch app on Heroku
        run: git push heroku ${{ github.ref_name }}:main --force
